GET http://localhost:3000/events

###

GET http://localhost:3000/events?startDate=2021-12-23&endDate=2021-12-25

###

POST http://localhost:3000/events
Content-Type: application/json

{
    "title": "Event 1",
    "description": "My first event",
    "date": "2021-12-24",
    "start_time": 540,
    "end_time": 630
}

###

PUT http://localhost:3000/events/5e18b61d-5ee3-4b20-a24c-5df1447d468b
Content-Type: application/json

{
    "title": "Event 2",
    "description": "My first event updated"
}

###

DELETE http://localhost:3000/events/34c07bc6-bc99-41e9-8829-d3927b47b03a